"""Final hero media for both sites, from the lossless 10-bit masters (hero_media_sweep.py masters):
- video: AV1 (10-bit), HEVC (10-bit, hvc1 for Safari) and H.264 (8-bit High) at 1080p and 720p, faststart, one GOP;
- posters: the master's first frame as AVIF and WebP at 1920 and 960 wide; a tiny blurred frame inlined as a data URI;
- every file named by a hash of its bytes (so it can be cached forever), and src/content/hero-media.ts listing them.
usage: SITE_DIR=<the site checkout> python make_hero_media.py
The masters are read from WORK_DIR (default: the folder you run from); files go to <site>/public and the manifest to
<site>/src/content/hero-media.ts."""
import base64, concurrent.futures as cf, hashlib, io, os, pathlib, shutil, subprocess
import imageio_ffmpeg
from PIL import Image, ImageFilter

FF = imageio_ffmpeg.get_ffmpeg_exe()
H = pathlib.Path(os.environ.get('WORK_DIR', '.'))  # where hero_media_sweep.py wrote the masters
SITE = pathlib.Path(os.environ.get('SITE_DIR', '.'))  # the site checkout
VID, IMG = SITE / 'public' / 'video' / 'hero', SITE / 'public' / 'img' / 'hero'
SITES = ['careers', 'playmakers']
CRF = {'av1': 26, 'hevc': 22, 'h264': 19}  # from the sweep: SSIM ~0.991 against the master, no banding
# size: (w, h, AV1 level, HEVC level, H.264 level, H.264 codec string)
SIZES = {'1080': (1920, 1080, '08', 'L120', '4.0', '640028'), '720': (1280, 720, '05', 'L93', '3.1', '64001F')}
ORDER = ['av1', 'hevc', 'h264']


def run(*a):
	subprocess.run([FF, '-v', 'error', '-y', *a], check=True)


def hashed(tmp: pathlib.Path, folder: pathlib.Path, stem: str, ext: str):
	name = f'{stem}.{hashlib.sha1(tmp.read_bytes()).hexdigest()[:8]}.{ext}'
	shutil.copy(tmp, folder / name)
	return name


def encode(job):
	site, size, codec = job
	w, h, av1, hevc, avcl, avcc = SIZES[size]
	src = H / f'master-{site}.mkv'
	tmp = H / 'final' / f'{site}-{size}.{codec}.mp4'
	vf = [] if size == '1080' else ['-vf', f'scale={w}:{h}:flags=lanczos']
	if codec == 'av1':
		args = ['-c:v', 'libaom-av1', '-crf', str(CRF['av1']), '-b:v', '0', '-cpu-used', '3', '-row-mt', '1', '-tiles', '2x2', '-pix_fmt', 'yuv420p10le', '-g', '192', '-keyint_min', '192']
		typ = f'video/mp4; codecs="av01.0.{av1}M.10"'
	elif codec == 'hevc':
		args = ['-c:v', 'libx265', '-preset', 'slower', '-crf', str(CRF['hevc']), '-pix_fmt', 'yuv420p10le', '-tag:v', 'hvc1', '-x265-params', 'aq-mode=3:keyint=192:min-keyint=192:no-open-gop=1:log-level=error']
		typ = f'video/mp4; codecs="hvc1.2.4.{hevc}.B0"'
	else:
		args = ['-c:v', 'libx264', '-preset', 'veryslow', '-crf', str(CRF['h264']), '-pix_fmt', 'yuv420p', '-profile:v', 'high', '-level', avcl, '-x264-params', 'aq-mode=3:keyint=192:min-keyint=192']
		typ = f'video/mp4; codecs="avc1.{avcc}"'
	run('-i', str(src), *vf, '-an', *args, '-movflags', '+faststart', str(tmp))
	return site, size, codec, f'/video/hero/{hashed(tmp, VID, f"{site}-{size}", f"{codec}.mp4")}', typ, tmp.stat().st_size / 1e6


def posters(site):
	src = H / f'master-{site}.mkv'
	out = {'avif': [], 'webp': []}
	for w, h in [(960, 540), (1920, 1080)]:
		a = H / 'final' / f'{site}-poster-{w}.avif'
		run('-i', str(src), '-frames:v', '1', '-vf', f'scale={w}:{h}:flags=lanczos', '-c:v', 'libaom-av1', '-still-picture', '1', '-crf', '20', '-pix_fmt', 'yuv420p10le', str(a))
		out['avif'].append(f'/img/hero/{hashed(a, IMG, f"{site}-{w}", "avif")}')
		p = H / 'final' / f'{site}-poster-{w}.webp'
		run('-i', str(src), '-frames:v', '1', '-vf', f'scale={w}:{h}:flags=lanczos', '-c:v', 'libwebp', '-quality', '90', '-compression_level', '6', str(p))
		out['webp'].append(f'/img/hero/{hashed(p, IMG, f"{site}-{w}", "webp")}')
	tiny = H / 'final' / f'{site}-tiny.png'
	run('-i', str(src), '-frames:v', '1', '-vf', 'scale=48:27:flags=area', str(tiny))
	buf = io.BytesIO()
	Image.open(tiny).convert('RGB').filter(ImageFilter.GaussianBlur(0.8)).save(buf, 'WEBP', quality=60)
	out['lqip'] = 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode()
	return site, out


if __name__ == '__main__':
	(H / 'final').mkdir(exist_ok=True)
	for d in (VID, IMG):
		d.mkdir(parents=True, exist_ok=True)
		for f in d.iterdir():
			f.unlink()
	jobs = [(s, z, c) for s in SITES for z in SIZES for c in ORDER]
	with cf.ThreadPoolExecutor(6) as ex:
		vids = list(ex.map(encode, jobs))
		pics = dict(ex.map(posters, SITES))
	for site, size, codec, src, typ, mb in vids:
		print(f'{site:10} {size:4} {codec:4} {mb:5.2f} MB  {src}')
	lines = [
		'// Generated by the hero media script (make_hero_media.py): every file is named by a hash of its',
		'// bytes, so it is cached for good. Video sources are in the order the browser should try them: AV1, HEVC, H.264.',
		'export type HeroVideo = { src: string; type: string }',
		'export type HeroMedia = { lqip: string; poster: { avif: [string, string]; webp: [string, string] }; video: { full: HeroVideo[]; small: HeroVideo[] } }',
		'',
		'export const HERO: Record<\'careers\' | \'playmakers\', HeroMedia> = {',
	]
	for site in SITES:
		v = {z: [(src, typ) for s, zz, c, src, typ, mb in vids if s == site and zz == z] for z in SIZES}
		v = {z: sorted(v[z], key=lambda t: ORDER.index(t[0].split('.')[-2])) for z in v}
		p = pics[site]
		lines += [
			f'\t{site}: {{',
			f"\t\tlqip: '{p['lqip']}',",
			f"\t\tposter: {{ avif: ['{p['avif'][0]}', '{p['avif'][1]}'], webp: ['{p['webp'][0]}', '{p['webp'][1]}'] }},",
			'\t\tvideo: {',
			'\t\t\tfull: [' + ', '.join(f"{{ src: '{s}', type: '{t}' }}" for s, t in v['1080']) + '],',
			'\t\t\tsmall: [' + ', '.join(f"{{ src: '{s}', type: '{t}' }}" for s, t in v['720']) + ']',
			'\t\t}',
			'\t},',
		]
	lines[-1] = lines[-1].rstrip(',')
	lines += ['}', '']
	(SITE / 'src' / 'content' / 'hero-media.ts').write_text('\n'.join(lines), encoding='utf-8')
	print('manifest written')
